Add a scope option to the query
vildanbina/laravel-model-json pull request #7
Opened 2024-09-10 09:28 UTC by RemiHin

This PR adds the ability to use the `--scope={scope}` option on exports.
If you have defined a scope on your model for example:
```php
    public function scopeActive(Builder $query): void
    {
        return $query->where('active', true);
    }
```
passing `--scope=active` to the export assures you only export the active models.

2024-09-18 16:21 UTC, vildanbina requested changes

2024-09-18 16:21 UTC, vildanbina commented on src/Traits/HasModel.php
> +        }
do you have any reason why this condition is here? Because an error will be thrown later in the query builder anyway when you try to call a non-existent scope

2024-09-18 16:21 UTC, vildanbina commented on src/Traits/HasModel.php
> +            ->when(!is_null($scope = $this->scope), function (Builder $builder) use ($scope) {
since `$this->scope` can be an empty string, and `is_null` would return `false` in that case, I would use the 
`->when(filled($this->scope), ...)` method instead. 

What do you think?

2024-09-19 12:54 UTC, RemiHin commented on src/Traits/HasModel.php
> +        }
My idea was to throw the exception early so we could pass the message, specifically, but you are right. Could be removed

2024-09-19 12:56 UTC, RemiHin commented on src/Traits/HasModel.php
> +            ->when(!is_null($scope = $this->scope), function (Builder $builder) use ($scope) {
agreed.

2024-09-19 13:13 UTC, vildanbina approved these changes

2024-09-19 13:13 UTC, merged

2024-09-19 13:16 UTC, vildanbina commented
@RemiHin this PR is approved and released on [v2.2](https://github.com/vildanbina/laravel-model-json/releases/tag/v2.2)

Thank you for your contribution!